# Generated by Django 4.2.7 on 2023-12-04 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feedback', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='ideas',
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
